name: "Raul Luzardo Professional Portfolio"
tagline: "Mechanical Engineering, Coding, and Personal Projects "
socials:
  linkedin: "https://www.linkedin.com/in/raul-luzardo/"
  instagram: "https://www.instagram.com/raul_luzardo13?igsh=MTVtamdlNGh1ZWI4Mw%3D%3D&utm_source=qr"
  email: "mailto:raluzardo04@gmail.com"
resume_path: "/assets/docs/raul-luzardo-resume.pdf"
