name: "Raul Luzardo"
tagline: "Mechanical Engineer & Supply Chain Strategist"
socials:
  linkedin: "https://www.linkedin.com/in/raul-luzardo"
  instagram: "https://www.instagram.com/raul.luzardo"
  email: "mailto:raul.luzardo@example.com"
resume_path: "/assets/docs/raul-luzardo-resume.pdf"
